### PR TITLE
Request timed out

### PR DESCRIPTION
**Pull request by EliuFlorez**
Request time 20 seg

### CODE REVIEW

**Comment by abraham** [comment]
10 seconds is more than enough for the default. Twitter responses are typically in the range of a second in my experience. If you want a different timeout you can use `$twitteroauth->setTimeouts(20, 20);`

**Comment by EliuFlorez** [comment]
ok @abraham perfect thanks

**Comment by magkopian** [comment]
@abraham Can you please add the `TwitterOAuth::setTimeouts()` method to the documentation? Yesterday, I spent a lot of time digging into the source code to find out if it was possible to change the timeout time and just now I noticed that there was a closed issue about this. I know the answer is inside the Config class but I think this could save people a little bit of time.

**Comment by EliuFlorez** [comment]
@magkopian +1

**Comment by abraham** [comment]
I'll see about getting that documented in the next week or two. The documentation is also open source if you have a moment to add it to `templates/index.html`. https://github.com/abraham/twitteroauth-demo

**Comment by magkopian** [comment]
@abraham Done. magkopian/twitteroauth-demo@f0e04e1eb03e962210f673cf8dc4b11d7d624a46

**Comment by abraham** [comment]
:thumbsup:

**Pull request closed without merging**
