### PR TITLE
Make apiHost and uploadHost configurable

### PR DESCRIPTION
**Pull request by TerjeBr**
The apiHost and uploadHost should be configurable in order to support functional tests where we mock out the twitter api.

### CODE REVIEW

**Comment by abraham** [comment]
Do you have examples of the types of tests you want to support?

**Comment by TerjeBr** [comment]
We have behat functional tests, where we mock out external services with wiremock(http://wiremock.org/).

**Comment by TerjeBr** [comment]
@abraham  do you consider merging this PR, or do you not want this change?

**Comment by TerjeBr** [comment]
I would appreciate some feedback. In a few days the company I work for will have to decide if we will use this component or not.

**Comment by abraham** [comment]
What about using the [WireMox proxy feature](http://wiremock.org/proxying.html)? You can tell TwitterOAuth to connect to your testing proxy and return recorded responses.

**Comment by TerjeBr** [comment]
We cannot use the proxy feature or anything in WireMock as long as TwitterOAuth is hardcoded to connect to https://api.twitter.com. Not without messing with DNS setup or hosts files in our testing environment, and we do not want to do that.

**Comment by abraham** [comment]
Additional flexibility similar to this will be included in v2.

**Comment by abraham** [comment]
It's not officially supported but you can override `apiUrl` in 3.1.0.

**Pull request closed without merging**
