### PR TITLE
added shield to RapidAPI

### PR DESCRIPTION
**Pull request by phillipseymor**
I've added a link in your README to Twitter's functions page in RapidAPI. I've done this for a few Twitter SDKs to help those who are reading the READMEs, understand and test the API before use.

### CODE REVIEW

**Comment by jtojnar** [comment]
This looks extremely fishy.

**Comment by phillipseymor** [comment]
@jtojnar Ah, not fishy, just a tool devs can use to explore the API before implementing your PHP library.

**Comment by jtojnar** [comment]
Are you affiliated with the site? Your GitHub history looks like you are paid for adding links to any API-related repo.

**Comment by phillipseymor** [comment]
I'm part of the RapidAPI team. We are trying to help developers better connect and test APIs.

**Comment by abraham** [comment]
The package linked to from that page is Node.js so this won't be helpful to TwitterOAuth developers.

**Pull request closed without merging**
