### PR TITLE
Allow Inheritance

### PR DESCRIPTION
**Pull request by hborras**
Changing some private methods to protected to allow inheritance without changing the original lib.

### CODE REVIEW

**Comment by abraham** [comment]
What reasons are you finding that require inheritance?

**Comment by plagueis** [comment]
For instance to request for different API_HOST without changing the lib, TwitterAds API for example.

Or implement different methods in GET/PUT.

**Comment by 0x46616c6b** [comment]
Then you should implement an abstract API class and concret classes for "normal" API and ads. But keep in mind to not break backward compatibility.

**Comment by abraham** [comment]
Pull requests that add Twitter Ads API support are welcome. I don't have access to the API so I don't know what the best way to do it would be. I've pinged t@twitterapi about access.

I don't know what you mean by "implement different methods in GET/PUT".

**Comment by plagueis** [comment]
@0x46616c6b Yes, it is another good idea. But I think we need to modify lib anyway. It's a good PR also.

@abraham You can see the documentation here https://dev.twitter.com/ads/overview 

It works in the same way with a different host and also with a sandbox host to make test.

When I said "GET/PUT" I wanted to say somethink like " if we want to add some stuff overriding the methods get,post or http. It was only an example.

**Comment by abraham** [comment]
Ads docs are only visible to those that have the API enabled.

**Comment by plagueis** [comment]
Are you sure?

I can access from my mobile without any logged account.

Also with an android emulator :S

**Comment by abraham** [comment]
I followed an Ads API method link earlier and it gave me an error. I guess it must have just been a broken link. Although I don't know if I'll be able to actually use the API.

**Comment by abraham** [comment]
Allowing additional configuration will be considered for v2.

**Comment by abraham** [comment]
It's not officially supported but you can override `apiUrl` in 3.1.0 to use other API hosts.

**Pull request closed without merging**
