### PR TITLE
Test all php files

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by abraham** [comment]
Why is this needed? What tests were not getting run before?

**Comment by paladox** [comment]
it tests all php file not just the test files.

**Comment by abraham** [comment]
Why is this needed?

**Comment by paladox** [comment]
Well not needed. But this will run all php file not just the tests.

**Comment by abraham** [comment]
Basically I'm trying to understand what purpose switching to a string of non-human readable cli flags provides. There is a pretty full set of functionality that should pretty much all get tested with `phpunit` and I want to understand why switching away from that would be better. You say it that it "will run all php files" but that's what it does not why it should be used.

**Comment by paladox** [comment]
Oh but I thought it runs only the test php files.

**Comment by abraham** [comment]
The test php files should be running all the rest of the php files but you still didn't answer why running your change would be better.

**Comment by paladox** [comment]
Well if the current way you do runs all the php file then my way would be pointless since this would do the same but if the current way only run the test then my way would be useful.

**Comment by abraham** [comment]
The test files should run pretty much the rest of the code.

**Pull request closed without merging**
