### PR TITLE
Fix for json_decode issue with Ubuntu PHP 5.5 JSON_BIGINT_AS_STRING bug

### PR DESCRIPTION
**Pull request by thaddeusmt**
This is related to issue #288, where calling `json_decode()` with the `JSON_BIGINT_AS_STRING` results in a "not implemented" error (even though it IS defined). I ran in to this running Ubuntu 14.04 with PHP 5.5.9 (PHP 5.5.9-1ubuntu4.5).

As mentioned in the original bug, it seems to be caused by Ubuntu now packaging pecl-json-c as an alias for php5-json due to licensing issues, and including a buggy version of it in the main distributions:
https://stackoverflow.com/questions/19520487/json-bigint-as-string-removed-in-php-5-5
https://bugs.php.net/bug.php?id=63520

I found a workaround by checking for the `JSON_C_VERSION` constant, which seems to be set by the alternative Ubuntu PHP implementation of `json_decode()`.

Also included in this pull request is an alternative handling of big JSON integers, and throwing some exceptions on decode errors.

Credit goes to the firebase/php-jwt project for a `preg_replace()` alternative to handle casting large ints and the error checking.
https://github.com/firebase/php-jwt/blob/master/Authentication/JWT.php

### CODE REVIEW

**Comment by abraham** [comment]
I'd be more inclined to update the `if` but do nothing if `JSON_BIGINT_AS_STRING` isn't supported. Twitter mostly recommends use of `id_str` anyways and using regex is just so fragile in general.

**Comment by abraham** [comment]
If people are still having issues maybe #11 could then be implemented so those who want can use a regex.

**Comment by thaddeusmt** [comment]
Fair enough, as Twitter does provide "id_str" for "id" and other large integer values.

Since I started using the regex from at JWT snippet in this pull request I found it has a few issues too (large integers in quoted strings preceded by a :), and I have not taken the time to conjure up a better one.

But I would recommend keeping the check for `JSON_C_VERSION` as this issue is present on a new, fully updated Ubuntu 14.04 / PHP 5.5 install.

I updated my fork to ditch the regex but kept the `if` and the Exception checking.

**Comment by abraham** [comment]
I left out the Exception handling for now. I'm deciding how I want to approach exceptions in general be for doing anything with them.

**Pull request closed without merging**
