### PR TITLE
[PSR-2] Rename underscore properties/variables, add docblocks for static analysis

### PR DESCRIPTION
**Pull request by 0x46616c6b**
This PR should not break any functionality, but I can't run the PHPUnit tests. Can you run the tests @abraham? In my mind its not right to call the api from twitter directly. We should mock all external requests, or?

### CODE REVIEW

**Comment by 0x46616c6b** [comment]
I must remove the cacert.pem and the usage of the chain in curl opts because it seems the actually CA which twitter uses is not included.

**Comment by abraham** [comment]
I haven't had any issues with cacert.pem. It was updated to the latest one used on Firefox last week.

**Comment by abraham** [comment]
Most of the src/* files other than TwitterOAuth.php and TwitterOAuthException.php probably shouldn't list me as author since they are originally from https://code.google.com/p/oauth

**Comment by 0x46616c6b** [comment]
Okay, I change that.

**Comment by 0x46616c6b** [comment]
Here the output, when I enable `CURLOPT_VERBOSE`.

    * Hostname was NOT found in DNS cache
    *   Trying 199.16.156.104...
    * Connected to api.twitter.com (199.16.156.104) port 443 (#0)
    * SSL: certificate verification failed (result: 5)
    * Closing connection 0
    
    * Hostname was found in DNS cache
    *   Trying 199.16.156.104...
    * Connected to api.twitter.com (199.16.156.104) port 443 (#0)
    * SSL: certificate verification failed (result: 5)
    * Closing connection 0

With the Proxy

    * Hostname was NOT found in DNS cache
    *   Trying 41.222.196.52...
    * Connected to 41.222.196.52 (41.222.196.52) port 8080 (#0)
    * Establish HTTP proxy tunnel to api.twitter.com:443

Possible that I get in europe an other server for api.twitter.com? Which IP you get when you resolve api.twitter.com?

**Comment by abraham** [comment]
* Connected to api.twitter.com (199.16.156.199) port 443 (#0)

**Pull request merged**
