### PR TITLE
Get image from DM

### PR DESCRIPTION
**Pull request by ericrkl**
Add function getimg to download immage attached to direct messages.

Modified function http.

### CODE REVIEW

**Comment by 9tN4tGi72j1z4Qe** [comment]
Hi Nice Day

**Comment by abraham** [comment]
I'm a little unsure what the purpose of this is. What Twitter API method is this for?

**Comment by 9tN4tGi72j1z4Qe** [comment]
Hi abraham

Having nice moments? Yes.
I am in the first stage and to this moments don't have more information about this...
With Best Regards
Abduallah Saeeid

**Comment by ericrkl** [comment]
It's not for a Twitter method per se, it's just to have a way to get and decode images sent in a direct message. I think is handy to "have it all" in one lib. 

From twittercommunity.com
"media shared in direct messages requires authorization to view. This authorization can be presented via an authenticated twitter.com session or by signing a request with the user's access token using OAuth 1.0A."

**Comment by aliriza0** [comment]
hello.twitter trend topic system update?.my system is no work.please help me

**Comment by abraham** [comment]
@aliriza0 if you are having problems please open a new issue.

**Comment by abraham** [comment]
@ericrkl I'm thinking about if this is the best approach, if it would make more sense to have a method that returns a signed URL for the developer to download as they choose, or some other approach.

**Comment by ericrkl** [comment]
As long as there’s a way to get the image from the URL in the end.

I made a social media customer care system for clients to interact with their audience (like Hoot Suite or Sprout), and it’s common for that audience to send some photo(s) as proof of some kind, via direct message (proof of purchase, or payment, or a photo from a damaged luggage to an airline, etc). These photos need to be downloaded and kept as a record of a conversation with some person. So it’s a very useful and commonly used operation.

—
Eric R Kelly
Whatsapp +1 (702) 879-7944

**Comment by ericrkl** [comment]
Great.

---
Eric R Kelly
Whatsapp +1(702) 879-7944

**Comment by ericrkl** [comment]
Just to let you know that I’m testing the new Twitter 30 day search API (now in private beta).

I’m using the PHP twitteroauth and first tests with GET method function perfectly.

—
Eric R Kelly
Whatsapp +1 (702) 879-7944

**Comment by abraham** [comment]
Related to #684 and #685.

**Comment by joelcuevas** [comment]
Does the "file" method propossal is still the preferred solution? I need to download DM files, if this is still valid, I could submit a PR in the next days.

**Comment by 9tN4tGi72j1z4Qe** [comment]
Hi abraham

I am pleased to inform you that , twitter stop our account after I moke
30000 follower of image's for twitter!
بتاريخ May 14, 2016 8:19 PM، كتبها "Abraham Williams" <
notifications@github.com>:

**Pull request closed without merging**
