### PR TITLE
changed media for media_data parameter on upload  (chunked) file request

### PR DESCRIPTION
**Pull request by iviamontes**
according with https://dev.twitter.com/rest/reference/post/media/upload-chunked, the base64-encoded file should be passed on the media_data,

I was not able to upload a chinked video until I changed to media_data, now it is working fine.

### CODE REVIEW

**Comment by abraham** [comment]
:+1: I've cherry-picked the relevant commit.

**Comment by iviamontes** [comment]
Could you please update your Packagist repository (I will remove mine) to be able to rollback my composer.json file and point to your?

**Comment by abraham** [comment]
Published v0.6.1.

**Comment by iviamontes** [comment]
thanks, I deleted mine.

**Pull request closed without merging**
