### PR TITLE
Support JSON POST bodies

### PR DESCRIPTION
**Pull request by abraham**
- [ ] Cleanup
- [ ] Add tests

### CODE REVIEW

**Comment by Nicolapps** [comment]
Can I provide any kind of help with this PR ?

**Comment by mpociot** [comment]
@abraham can I help you with this PR? Would love to use your library in combination with [BotMan](https://github.com/botman/botman). The PR changes work perfectly for me.

**Comment by mpociot** [comment]
Hi @abraham - you're probably extremely busy, but I still wanted to ask you if I can help you with this or if you happen to know a timeframe at which you want to look into this PR.

Thank you!

**Comment by mathiasmoeller** [comment]
Are there any news on the json feature?

**Comment by kinoute** [comment]
Interested by this as well. The _direct_messages/new_ endpoint will be deprecated on June 19th.

https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/guides/direct-message-migration

**Comment by abraham** [comment]
This is now released in v0.9.

**Pull request closed without merging**
