### PR TITLE
Accessing string offsets using curly braces has been deprecated in PHP 7.4.

### PR DESCRIPTION
**Pull request by hkiciy**
Replace curly brackets to square brackets.

### CODE REVIEW

**Comment by norbertmocsnik** [comment]
Looking forward to this fix

**Comment by norbertmocsnik** [comment]
PHP 7.4 throws

> Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/web/vendor/abraham/twitteroauth/src/SignatureMethod.php on line 61

**Comment by abraham** [comment]
Thanks!

**Comment by tolry** [comment]
Hi @abraham, 

if I'm not mistaken, this change hasn't been published yet, right? Could you please make a release for this? I would prefer a release over `dev-master` in my `composer.json`  in order to have this working without deprecation warnings in php 7.4.

Thanks for a great library! :+1:

**Comment by tolry** [comment]
Sorry, I just saw that this has only been merged a couple of days ago (previously only looked at the commit date) - no need to rush here, I will pin to a commit hash for now :-)

**Comment by abraham** [comment]
These changes should already be released under v1.1.0.

**Comment by tolry** [comment]
Thanks for the reply ... :thinking: strange with `^1.1.0` it seems to work, with my old version constraint it didn't work, sorry for the hassle

**Comment by akshayshrivastav866** [comment]
i am still getting this error, any update yet?

**Comment by UVLabs** [comment]
@akshayshrivastav866 You'd have to update to v1.0.1, I checked the code for that tag and it doesn't seem like the curly brackets still exist

**Pull request merged**
