### PR TITLE
Allow the consumer key to be updated after initialization

### PR DESCRIPTION
**Pull request by ollietb**
I need to update the consumer key from a child class but this isn't possible because of the scope of the consumer property. I've just added some utility methods to allow for the consumer to be updated after the object is initialized.

### CODE REVIEW

**Comment by ollietb** [comment]
@abraham could this be merged in?

**Comment by abraham** [comment]
Why not just create a new TwitterOAuth object instead of updating. This just adds additional methods that would need to be tested and maintained and edge cases where you have a user's access_token set but change the consumer key to one that does not match the access_token.

**Comment by abraham** [comment]
I think it's easy enough to just create a new TwitterOAuth instance.

**Comment by ollietb** [comment]
@abraham I mostly use the dependency injection pattern to insert the TwitterOAuth class into the constructor, so creating new instances in my other services makes my code hard to test and reduces DRY principles

**Comment by abraham** [comment]
Can you give a more concrete code example?

**Comment by ollietb** [comment]
```php
class TwitterOauthManager {

protected $twitter
/**
* The TwitterOAuth service is constructed in the dependency injection container with 
* the settings from a config file
**/
public function __construct(TwitterOAuth $twitter) {
    $this->twitter = $twitter;
}
 /**
  * @param $consumerKey
  * @param $consumerSecret
  */
public function updateConsumer($consumerKey, $consumerSecret) {
    $this->twitter->setConsumer($consumerKey, $consumerSecret);
}
}
```

In this example the TwitterOAuth class can easily be replaced by a mock. If the class was initialised in this service it would be hard to test and keep separation of concerns

**Comment by ollietb** [comment]
This is the real life usage of this method in our codebase. We maintain users across many sites with different oauth permissions/setup on each but the fetching of Twitter data is all handled through a central message queue, which is why we need to update the consumer key each time.

```php
class TwitterApi extends TwitterOAuth implements FetcherApiInterface, HasPrivateUsersInterface
{
   ...

    /**
     * @param Site $site
     * @param int $extendedPermissions
     */
    public function updateConsumerKeyForSite(Site $site, $extendedPermissions = 0)
    {
        list($consumerKey, $consumerSecret) = $this->consumerKeyService->getKeyForSite($site->getSitename(), $extendedPermissions == User::EXTENDED_PERMISSIONS_TWITTER_POST);

        $this->setConsumer($consumerKey, $consumerSecret);
    }

    /**
     * {@inheritdoc}
     */
    public function setAccessToken(AbstractToken $token = null)
    {
        if (!$token instanceof TwitterToken) {
            if (is_object($token)) {
                throw new InvalidAccessTokenException(sprintf('Access token of type %s is invalid', get_class($token)));
            } else {
                throw new AccessTokenNotFoundException('Cannot set with a null token');
            }
        }
        $this->accessToken = $token;

        $this->setOAuthToken($token->getKey(), $token->getSecret());

        if ($token->getSite()) {
            $this->updateConsumerKeyForSite($token->getSite(), $token->getExtendedPermissions());
        }
    }

    ...
}
```

**Pull request closed without merging**
