### PR TITLE
Twitter API latency suddenly got a lot worse last week

### PR DESCRIPTION
**Pull request by indorock**
increase default timeouts to allow more time for data to return to overseas connections.

### CODE REVIEW

**Comment by abraham** [comment]
Check "Changing timeout settings" on https://twitteroauth.com/

**Comment by indorock** [comment]
I understand the defaults can be overridden but in many cases (such as ours) the defaults have been working, for months now. Up until just this week. It took about 3-4 hours of debugging to find out why unit tests were failing. Before last week, never, but now, they consistently fail, between different environments, so something clearly has gotten slower on Twitter's end. Instead of subjecting other European apps to the same waste of time I thought it would be beneficial to just crank up the defaults.

**Comment by abraham** [comment]
I'm guessing it's not Twitter's end but the overseas connection is having transient issues. If that's the case this isn't really fixing anything. Next week there would be more congestion that causes the connections to take 30 seconds.

**Comment by Agistopolis** [comment]
I wonder if this is causing the "name lookup timed out" error we got a few times now. 

Abraham\TwitterOAuth\TwitterOAuthException: name lookup timed out in Abraham\TwitterOAuth\TwitterOAuth->request()

If that is the case what can I do to fix this?

Thanks
Agis

**Pull request closed without merging**
