### PR TITLE
Update TwitterOAuth.php

### PR DESCRIPTION
**Pull request by morrislaptop**
Add option to set the chunk size

### CODE REVIEW

**Comment by abraham** [comment]
What are the use cases for having a configurable chunksize?

**Comment by morrislaptop** [comment]
Uploading 5MB files 40KB at a time is incredibly inefficient for a server with a fast connection to Twitter - this option would allow the developer to set the upload chunk that is suitable for their situation.

**Comment by clphillips** [comment]
+1 for this, but the implementation is bad. A better option would be:

```php
$chunk_size = array_key_exists('chunk_size', $parameters)
    ? $parameters['chunk_size']
    : self::UPLOAD_CHUNK;

// ...
                'media_data' => base64_encode(fread($media, $chunk_size))
// ...
```

**Comment by abraham** [comment]
Requested changes haven't been made. Feel free to reopen if you want to update the PR.

**Pull request closed without merging**
